global ds9
global buttons
global pbuttons
global samp
global tcl_platform

proc InitASDF {asdf_tmp_dir_arg} {
    global asdf_pid
    global asdf_tmp_dir
    global ds9pid
  
    set asdf_pid -1
    set asdf_tmp_dir $asdf_tmp_dir_arg

}

proc CheckPID {pid} {
    global tcl_platform
    set OS [lindex $tcl_platform(os) 0]
    if {$OS == "Darwin"} {
        if {[catch {exec ps -p $pid}]} {
            return "notrunning"
        } else {
            return "running"
        }
    }
}

proc AsdfFileAccess {pds9_python} {
    global asdf_pid
    global asdf_tmp_dir
        # Check that there is dialog is present by checking the pid's existance
        if {[CheckPID $asdf_pid] == "running"} {
            # Signal that it should be raised over other windows
            set fid [open "${asdf_tmp_dir}/ds9cmd" w]
            puts $fid "raise"
            close $fid
            return
        } else {
            # Create the python process and dialog
            set asdf_pid [exec $pds9_python -m pds9 [pid] &]
        }
}
package provide DS9 1.0

InitASDF "[glob ~/ds9tmp]"
ButtonButton $ds9(buttons).file.asdf asdf [list AsdfFileAccess $pds9_python]
set pbuttons(file,asdf) 1
append buttons(file) "$ds9(buttons).file.asdf pbuttons(file,asdf)"
LayoutButtons
